
    - name: Remove immutable flag if it exists (unlock file)
      command: chattr -i /etc/resolv.conf
      ignore_errors: yes
      changed_when: false
      

    - name: Delete existing resolv.conf (removes symlinks)
      file:
        path: /etc/resolv.conf
        state: absent
      
      
    - name: Create new static resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          search {{ dns_search }}
          nameserver {{ local_dns_IPv4 }}
          options timeout:2 attempts:3
        owner: root
        group: root
        mode: '0644'
      
    - name: Add hostname mapping
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ inventory_hostname }}"
        insertafter: '^127\.0\.0\.1\s+localhost'

    - name: Re-apply immutable flag (prevent DHCP/System overwrite)
      command: chattr +i /etc/resolv.conf
      ignore_errors: yes
      
