argocd.ncs-cloud.lan 172.16.20.176	
bastion-server.ncs-cloud.lan 172.16.20.176
dns.ncs-cloud.lan 172.16.20.176
wireguard.ncs-cloud.lan 172.16.20.176
fproxy.ncs-cloud.lan 172.16.20.176
vault.ncs-cloud.lan  172.16.20.176
filer.seaweedfs.ncs-cloud.lan 
gitlab.ncs-cloud.lan 172.16.20.176
grafana.ncs-cloud.lan 172.16.20.176
hubble.ncs-cloud.lan 172.16.20.176
master.seaweedfs.ncs-cloud.lan 172.16.20.176
prometheus.ncs-cloud.lan 172.16.20.176
s3.seaweedfs.ncs-cloud.lan  172.16.20.176
uptime.ncs-cloud.lan 172.16.20.176


argocd.internal.ncs-cloud.lan   10.10.30.193 #cilium gateway	
bastion-server.internal.ncs-cloud.lan   10.10.10.10
cloud-services.internal.ncs-cloud.lan   10.10.40.3
dns.internal.ncs-cloud.lan   10.10.40.3       # pi-hole     
wireguard.internal.ncs-cloud.lan 10.10.40.3
fproxy.internal.ncs-cloud.lan 10.10.10.10 # squid
vault.internal.ncs-cloud.lan	10.10.40.4	# cluster vault
filer.seaweedfs.internal.ncs-cloud.lan 	10.10.20.3
gitlab-server.internal.ncs-cloud.lan	10.10.20.4	
gpu-worker-01.internal.ncs-cloud.lan 10.10.30.10
grafana.internal.ncs-cloud.lan 10.10.30.193 #cilium gateway
hubble.internal.ncs-cloud.lan 10.10.30.193 #cilium gateway
inference-worker-01.internal.ncs-cloud.lan	10.10.30.13	
k3s-master-01.internal.ncs-cloud.lan	10.10.30.3
k3s-worker-01.internal.ncs-cloud.lan	10.10.30.11	
k3s-worker-02.internal.ncs-cloud.lan	10.10.30.12		
master.seaweedfs.internal.ncs-cloud.lan	10.10.20.3
mgmt-vault.internal.ncs-cloud.lan  10.10.10.4
prometheus.internal.ncs-cloud.lan	10.10.30.193 #clium gateway	
s3.seaweedfs.internal.ncs-cloud.lan	10.10.20.3	
seaweedfs.internal.ncs-cloud.lan 10.10.20.3
uptime.internal.ncs-cloud.lan 10.10.40.3


