argocd.ncs-cloud.lan 172.16.20.78	
bastion-server.ncs-cloud.lan 172.16.20.78
dns.ncs-cloud.lan 172.16.20.78
wireguard.ncs-cloud.lan 172.16.20.78
fproxy.ncs-cloud.lan 172.16.20.78
vault.ncs-cloud.lan  172.16.20.78
filer.seaweedfs.ncs-cloud.lan 
gitlab.ncs-cloud.lan 172.16.20.78
grafana.ncs-cloud.lan 172.16.20.78
hubble.ncs-cloud.lan 172.16.20.78
master.seaweedfs.ncs-cloud.lan 172.16.20.78
prometheus.ncs-cloud.lan 172.16.20.78
s3.seaweedfs.ncs-cloud.lan  172.16.20.78
uptime.ncs-cloud.lan 172.16.20.78


argocd.internal.ncs-cloud.lan   10.10.30.193	
bastion-server.internal.ncs-cloud.lan   10.10.10.10
cloud-services.internal.ncs-cloud.lan   10.10.40.10
dns.internal.ncs-cloud.lan   10.10.40.10       # pi-hole     
wireguard.internal.ncs-cloud.lan 10.10.40.10
fproxy.internal.ncs-cloud.lan 10.10.40.10 # squid
vault.internal.ncs-cloud.lan	10.10.20.100	# cluster vault
filer.seaweedfs.internal.ncs-cloud.lan 	10.10.20.10
gitlab-server.internal.ncs-cloud.lan	10.10.20.5	
gpu-worker-01.internal.ncs-cloud.lan 10.10.30.10
grafana.internal.ncs-cloud.lan 10.10.30.193 #cilium gateway
hubble.internal.ncs-cloud.lan 10.10.30.193 #cilium gateway
inference-worker-01.internal.ncs-cloud.lan	10.10.30.15	
k3s-master-01.internal.ncs-cloud.lan	10.10.30.5
k3s-worker-01.internal.ncs-cloud.lan	10.10.30.20	
k3s-worker-02.internal.ncs-cloud.lan	10.10.30.21		
master.seaweedfs.internal.ncs-cloud.lan	10.10.20.10		
mgmt-vault.internal.ncs-cloud.lan  10.10.10.100
prometheus.internal.ncs-cloud.lan	10.10.30.193 #clium gateway	
s3.seaweedfs.internal.ncs-cloud.lan	10.10.20.10	
seaweedfs.internal.ncs-cloud.lan 10.10.20.10
uptim.internal.ncs-cloud.lan 10.10.40.10


