---
- name: Install and Configure Bastion Proxies
  hosts: bastion_server
  become: yes
  tags:
    - proxy
  vars_files: 
    - ../../../secrets/vault.yml   
    - ../../../vars.yml   
  vars:
    ssl_dir: /etc/nginx/ssl/selfsigned
    ca_key: "{{ ssl_dir }}/ncs-root-ca.key"
    ca_cert: "{{ ssl_dir }}/ncs-root-ca.crt"
    ca_config: "{{ ssl_dir }}/ncs-root-ca.cnf"

    server_cert: "{{ ssl_dir }}/fullchain.pem"
    server_key: "{{ ssl_dir }}/privkey.pem"
    server_csr: "{{ ssl_dir }}/ncs-cloud.csr"
    server_config: "{{ ssl_dir }}/ncs-cloud.cnf"


  tasks:
    
    - name: Configure DNS records
      include_tasks: "../security/dns_config_task.yml"

    - name: Install Nginx and Squid
      apt:
        name: [nginx, squid]
        state: present
        update_cache: yes

    - name: Create SSL directory
      file:
        path: "{{ ssl_dir }}"
        state: directory
        mode: '0700'

    # --- STEP 1: CREATE THE ROOT CA ---
    - name: Create CA Config File
      copy:
        dest: "{{ ca_config }}"
        content: |
          [ req ]
          distinguished_name = req_distinguished_name
          x509_extensions = v3_ca
          prompt = no
          [ req_distinguished_name ]
          CN = NCS Internal Root CA
          [ v3_ca ]
          basicConstraints = critical,CA:TRUE
          keyUsage = critical,keyCertSign,cRLSign
          subjectKeyIdentifier = hash

    - name: Create Root CA Private Key
      community.crypto.openssl_privatekey:
        path: "{{ ca_key }}"
        size: 4096

    - name: Check if CA certificate already exists
      stat:
        path: "{{ ca_cert }}"
      register: ca_cert_stat

    - name: Generate Root CA Certificate with Extensions
      shell: |
        openssl req -x509 -new -nodes \
          -key {{ ca_key }} \
          -sha256 -days 3650 \
          -out {{ ca_cert }} \
          -extfile {{ ca_config }} \
          -extensions v3_ca
      when: not ca_cert_stat.stat.exists
        

    # --- STEP 2: CREATE SIGNED SERVER CERT ---
    - name: Create Server Extension Config
      copy:
        dest: "{{ server_config }}"
        content: |
          [ v3_ca ]
          authorityKeyIdentifier=keyid,issuer
          basicConstraints=CA:FALSE
          keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
          subjectAltName = @alt_names
          
          [alt_names]
          DNS.1 = ncs-cloud.lan
          DNS.2 = *.ncs-cloud.lan
          DNS.3 = localhost
          IP.1 = 127.0.0.1

    - name: Create Server Private Key
      community.crypto.openssl_privatekey:
        path: "{{ server_key }}"
        size: 2048

    - name: Create Server CSR
      community.crypto.openssl_csr:
        path: "{{ server_csr }}"
        privatekey_path: "{{ server_key }}"
        common_name: "ncs-cloud.lan"
        subject_alt_name:
          - "DNS:ncs-cloud.lan"
          - "DNS:*.ncs-cloud.lan"
          - "DNS:localhost"
          - "IP:127.0.0.1"
    
    - name: Check if server certificate exists
      stat:
        path: "{{ server_cert }}"
      register: server_cert_stat

    - name: Sign Server Certificate with CA extensions
      shell: |
        openssl x509 -req \
        -in {{ server_csr }} \
        -CA {{ ca_cert }} \
        -CAkey {{ ca_key }} \
        -CAcreateserial \
        -out {{ server_cert }} \
        -days 365 \
        -sha256 \
        -extfile {{ server_config }} \
        -extensions v3_ca
      when: not server_cert_stat.stat.exists

    - name: Configure Nginx proxy header hash sizes
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: 'http {'
        line: "    {{ item }}"
        state: present
      loop:
        - "proxy_headers_hash_max_size 1024;"
        - "proxy_headers_hash_bucket_size 128;"
#========================GITLAB====================================================
    - name: Configure GitLab proxy
      include_tasks: "../security/proxy_task/gitlab.yml"

#============================SEAWEEDFS=======================================================
    - name: Configure Seaweedfs proxy
      include_tasks: "../security/proxy_task/seaweedfs.yml"

#==========================PI-HOLE============================================
    - name: Configure dns proxy
      include_tasks: "../security/proxy_task/pihole.yml"

#==========================Up-time============================================
    - name: Configure uptime proxy
      include_tasks: "../security/proxy_task/uptime.yml"

#==========================Vault============================================
    - name: Configure vault proxy
      include_tasks: "../security/proxy_task/vault.yml"

#==========================Keycloak============================================
    - name: Configure keycloak proxy
      include_tasks: "../security/proxy_task/keycloak.yml"

#==========================K3s_config_task ============================================
    - name: Configure proxy routes for k3s gateway
      include_tasks: "../security/proxy_task/k3s.yml"

#======================================================================================
    - name: Remove Default Nginx Site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    # --- SQUID CONFIGURATION (Forward Proxy) ---

    - name: Configure Squid to allow internal network
      blockinfile:
        path: /etc/squid/squid.conf
        insertbefore: "http_access deny all"
        block: |
          acl internal_net src {{ internal_network }}
          http_access allow internal_net
          http_port 3128

    # --- SERVICE MANAGEMENT ---
    # - name: Restart Nginx and Squid
    #   systemd:
    #     name: "{{ item }}"
    #     state: restarted
    #     enabled: yes
    #   loop:
    #     - nginx
    #     # - squid

  handlers:
    - name: validate nginx config
      command: nginx -t
      listen: "nginx config changed"
      changed_when: false

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
      listen: "nginx config changed"
