
#==========================ArgoCD============================================
    - name: Configure Services  access (ArgoCD)
      copy:
        dest: /etc/nginx/sites-available/argocd-proxy
        content: |
            server {
                listen 80;
                server_name {{ argocd_external_url }};
                resolver {{ local_dns_IPv4 }} valid=30s;

                location / {   
                    set $upstream_service "http://{{ argocd_url }}";
                    proxy_pass $upstream_service;

                    # Standard Proxy Headers
                    proxy_set_header Host {{ argocd_url }};
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                    # This is the "Secret Sauce" for ArgoCD UI/API
                    proxy_set_header X-Forwarded-Proto $scheme;

                    # WebSocket support (Required for ArgoCD terminal and logs)
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";

                    proxy_connect_timeout 60s;
                    proxy_send_timeout 60s;
                    proxy_read_timeout 60s;

                    client_max_body_size 10M;
                }
            }
      notify: "nginx config changed"

    - name: Enable argocd proxy site
      file:
        src: /etc/nginx/sites-available/argocd-proxy
        dest: /etc/nginx/sites-enabled/argocd-proxy
        state: link
      notify: "nginx config changed"


#==========================Hubble============================================
    - name: Configure Services  access (Hubble)
      copy:
        dest: /etc/nginx/sites-available/hubble-proxy
        content: |
            server {
                listen 80;
                server_name {{ hubble_external_url }};
                resolver {{ local_dns_IPv4 }} valid=30s;

                location / {   
                    set $upstream_service "http://{{ hubble_url }}";
                    proxy_pass $upstream_service;

                    # Standard Proxy Headers
                    proxy_set_header Host {{ hubble_url }};
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                    # This is the "Secret Sauce" for Hubble UI/API
                    proxy_set_header X-Forwarded-Proto $scheme;

                    # WebSocket support 
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";

                    proxy_connect_timeout 60s;
                    proxy_send_timeout 60s;
                    proxy_read_timeout 60s;

                    client_max_body_size 10M;
                }
            }
      notify: "nginx config changed"

    - name: Enable hubble proxy site
      file:
        src: /etc/nginx/sites-available/hubble-proxy
        dest: /etc/nginx/sites-enabled/hubble-proxy
        state: link
      notify: "nginx config changed"



#==========================Grafana============================================
    - name: Configure Services  access (Grafana)
      copy:
        dest: /etc/nginx/sites-available/grafana-proxy
        content: |
            server {
                listen 80;
                server_name {{ grafana_external_url }};
                resolver {{ local_dns_IPv4 }} valid=30s;

                location / {   
                    set $upstream_service "http://{{ grafana_url }}";
                    proxy_pass $upstream_service;

                    # Standard Proxy Headers
                    proxy_set_header Host {{ grafana_url }};
                    proxy_set_header X-Forwarded-Server $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                    # This is the "Secret Sauce" for Grafana UI/API
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_set_header Origin http://{{ grafana_url }};

                    # WebSocket support 
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";

                    proxy_connect_timeout 60s;
                    proxy_send_timeout 60s;
                    proxy_read_timeout 60s;

                    client_max_body_size 10M;

                }
            }
      notify: "nginx config changed"

    - name: Enable grafana proxy site
      file:
        src: /etc/nginx/sites-available/grafana-proxy
        dest: /etc/nginx/sites-enabled/grafana-proxy
        state: link
      notify: "nginx config changed"  