
[cloud_services]
cloud-services ansible_host=10.10.40.3 ansible_user=ubuntu


#------------------------------------------------------------
[gitlab_server]
gitlab-server ansible_host=10.10.20.4 ansible_user=ubuntu

#------------------------------------------------------------

[vaults_vms]
cluster-vault ansible_host=10.10.40.4 ansible_user=ubuntu
mgmt-vault ansible_host=10.10.10.4 ansible_user=ubuntu


[mgmt_vault]
mgmt-vault ansible_host=10.10.10.4 ansible_user=ubuntu


[mgmt_vault:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@bastion-server"'

[cluster_vault]
cluster-vault ansible_host=10.10.40.4 ansible_user=ubuntu

[cluster_vault:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@bastion-server"'


[seaweedfs_servers]
seaweedfs ansible_host=10.10.20.3 ansible_user=ubuntu



[k3s_servers]
k3s-master-01 ansible_host=10.10.30.3
gpu-worker-01 ansible_host=10.10.30.10
k3s-worker-01 ansible_host=10.10.30.11
k3s-worker-02 ansible_host=10.10.30.12 
inference-worker-01 ansible_host=10.10.30.13

[k3s_servers:vars] 
ansible_user=ubuntu

[k3s_master]
k3s-master-01 ansible_host=10.10.30.3


[all_vms]
k3s-master-01 ansible_host=10.10.30.3 ansible_user=ubuntu
gpu-worker-01 ansible_host=10.10.30.10 ansible_user=ubuntu
inference-worker-01 ansible_host=10.10.30.13 ansible_user=ubuntu
k3s-worker-01 ansible_host=10.10.30.11 ansible_user=ubuntu
k3s-worker-02 ansible_host=10.10.30.12 ansible_user=ubuntu
cloud-services ansible_host=10.10.40.3 ansible_user=ubuntu
seaweedfs ansible_host=10.10.20.2 ansible_user=ubuntu
cluster-vault ansible_host=10.10.40.4 ansible_user=ubuntu
mgmt-vault ansible_host=10.10.10.4 ansible_user=ubuntu
gitlab-server ansible_host=10.10.20.4 ansible_user=ubuntu


 

# BEGIN ANSIBLE MANAGED BLOCK
[bastion_server]
bastion-server ansible_host=172.16.20.176 ansible_user=ubuntu
# END ANSIBLE MANAGED BLOCK
