[k3s_servers]
k3s-master-01 ansible_host=10.0.0.5
gpu-worker-01 ansible_host=10.0.0.4
k3s-worker-01 ansible_host=10.0.0.3

[k3s_servers:vars] 
ansible_user=ubuntu

#------------------------------------------------------------
[gitlab_server]
gitlab-server ansible_host=10.0.0.6 ansible_user=ubuntu

#------------------------------------------------------------

[all_vms]
k3s-master-01 ansible_host=10.0.0.5 ansible_user=ubuntu
gpu-worker-01 ansible_host=10.0.0.4 ansible_user=ubuntu
k3s-worker-01 ansible_host=10.0.0.3 ansible_user=ubuntu




