
---
#--------------------------------------------------------------------------------#
# Load default secrets to bootstrap applications
# ********** DEPENDS ON k3s_vault_config.yml ********************
#--------------------------------------------------------------------------------#
- name: Preload Vault
  hosts: cluster-vault
  vars_files: 
    - "../../../../secrets/vault.yml" 
    - "../../../../secrets/cluster_recovery.yml" 
    - "../../../vars.yml"    
  tags:
    - preload-vault

  vars:
    grafana_path: ""
  environment:
        VAULT_ADDR: "http://127.0.0.1:8200"
        VAULT_TOKEN: "{{ root_token }}"
        VAULT_SKIP_VERIFY: true
  tasks:
   
#==================================================POLICIES=====================================
    - name: Create grafana Policies
      shell: |
        vault policy write  'monitoring-policy' - <<EOF
        path "secret/data/monitoring/*" {
          capabilities = ["read", "list"]
        }
        # Also grant access to the specific key if needed
        path "secret/data/monitoring" {
          capabilities = ["read"]
        }
        EOF
      no_log: true 

    - name: Create Gitlab-runner Policies
      shell: |
        vault policy write  'gitlab-runner-policy' - <<EOF
        path "secret/data/gitlab-runner/*" {
          capabilities = ["read", "list"]
        }
        # Also grant access to the specific key if needed
        path "secret/data/gitlab-runner/registration" {
          capabilities = ["read"]
        }
        EOF
      no_log: true 

    - name: Create ArgoCD  policy via CLI
      shell: |
        vault policy write argocd-policy - <<EOF
        
        # 1. Self-management
        path "auth/token/renew-self" {
          capabilities = ["update"]
        }
        path "auth/token/lookup-self" {
          capabilities = ["read"]
        }

        # 2. Data access
        path "secret/data/argocd/gitlab" {
          capabilities = ["create", "read", "update", "delete", "list"]
        }

        # 3. Discovery – required for preflight check
        path "secret/argocd/gitlab" {
          capabilities = ["read", "list"]
        }

        # 4. Metadata for listing
        path "secret/metadata/argocd/gitlab" {
          capabilities = ["list", "read"]
        }
        path "secret/metadata/argocd/" {
          capabilities = ["list"]
        }
        EOF
      no_log: true 



#==================================================ROLES=====================================

    - name: Create Unified Kubernetes Auth Role
      shell: |
        vault write 'auth/kubernetes/role/cluster-ops-role' \
            bound_service_account_names="external-secrets,argocd-repo-server,argocd-server,argocd-application-controller" \
            bound_service_account_namespaces="external-secrets,argocd,monitoring" \
            policies="monitoring-policy,gitlab-runner-policy,argocd-policy" \
            ttl="1h" 
      no_log: true 
            
#==================================================Load Secretes=====================================
       
    - name: Write Grafana credentials to Vault
      shell: >
        vault kv put 'secret/monitoring/grafana-admin' 
        admin-user='{{ grafana_user }}' 
        admin-password='{{ grafana_password }}'
      no_log: true  # Prevents the password from appearing in the terminal output
      
    - name: Write Gitlab-runner credentials to Vault
      shell: >
        vault kv put 'secret/gitlab-runner/registration' 
        token='{{ gitlab_runner_token }}' 
      # no_log: true 

    - name: Write GitLab group token into Vault KV2 via CLI
      shell: |
        vault kv put secret/argocd/gitlab \
          url="{{ gitlab_repo_url }}" \
          username="{{ gitlab_user }}" \
          password="{{ gitlab_group_token }}" \
          group="{{ gitlab_group_name }}"
      no_log: true 
