---
- name: Provision OpenStack Network on NCS
  hosts: localhost
  gather_facts: false
  vars:
    # Match these to your environment
    cloud_name: NCS #Ntiamoah cloud services
    network_name: k3s-private-net
    subnet_name: k3s-private-subnet
    cidr: 10.0.0.0/24
    external_network_name: "public-vlan20"
    gateway: main-gateway-router

   

  tasks:
    # 1. Create the Private Network
    - name: Create Private Network
      openstack.cloud.network:
        name: "{{ network_name }}"
        state: present

    # 2. Create the Subnet
    - name: Create Private Subnet
      openstack.cloud.subnet:
        network_name: "{{ network_name }}"
        name: "{{ subnet_name }}"
        cidr: "{{ cidr }}"
        dns_nameservers:
          - 8.8.8.8
          - 1.1.1.1
        state: present
  

    - name: Connect Private Subnet to Gateway
      openstack.cloud.router:
        state: present
        name: "{{gateway}}"
        interfaces: 
          - "{{subnet_name}}"
    