---
#--------------------------------------------------------------------------------#
# Setup vm nodes with terraform
#--------------------------------------------------------------------------------#
- name: Set up vm nodes with terraform
  hosts: localhost
  vars_files: 
    - ../../../../secrets/vault.yml   
    - ../../../vars.yml    
  tags:
    - blue-print
  tasks:
    - name: Deploy the blue-print
      community.general.terraform:
        project_path: "../../../../terraform/blue-print"
        state: present
        force_init: yes
        variables:
          mgmt_net_range: "{{ mgmt_net_range }}"
          mgmt_net: "{{ mgmt_net }}"
          data_net_range: "{{ date_net_range }}"
          data_net: "{{ data_net }}"
          service_net_range: "{{ service_net_range }}"
          service_net: "{{ service_net }}"
          k3s_net_range: "{{ k3s_net_range }}"
          k3s_net: "{{ k3s_net }}"
          key_pair_file: "{{ local_public_key }}"
          public_cidr:  "{{ public_cidr }}"
          physical_router_gateway_ip:  "{{ physical_router_gateway_ip }}"
          public_allocation_pool_start:  "{{ public_allocation_pool_start }}"
          public_allocation_pool_end:  "{{ public_allocation_pool_end }}"
          dns_local_ip:  "{{ local_dns_IPv4 }}"
