---
#--------------------------------------------------------------------------------#
# Setup compute flavors for the infrastructure
#--------------------------------------------------------------------------------#
- name: Create compute flavors
  hosts: localhost
  vars_files: 
    - ../../../../secrets/vault.yml   
    - ../../../../vars.yml    
  tags:
    - blue-print
    - flavors
  tasks:
    - name: Create compute flavors
      community.general.terraform:
        project_path: "../../../../terraform/flavors"
        state: present
        force_init: yes
        