---
#--------------------------------------------------------------------------------#
# Setup vm nodes with terraform
#--------------------------------------------------------------------------------#
- name: Set up vm nodes with terraform
  hosts: localhost
  vars_files: 
    - ../../../../secrets/vault.yml   
    - ../../../vars.yml    
  tags:
    - blue-print
    - security-group
  tasks:
    - name: Deploy the security-groups
      community.general.terraform:
        project_path: "../../../../terraform/security-groups"
        state: present
        force_init: yes
        variables:
          internal_network: "{{ internal_network }}"
