---
#--------------------------------------------------------------------------------#
# Setup vm nodes with terraform
#--------------------------------------------------------------------------------#
- name: Set up vm nodes with terraform
  hosts: localhost
  vars_files: 
    - ../../../secrets/vault.yml   
    - ../../../vars.yml    
  tags:
    - jumpbox
  tasks:
    - name: Deploy the jumpbox
      community.general.terraform:
        project_path: "../../../../terraform/jumpbox"
        state: present
        force_init: yes
        variables:
          auth_url: "{{ os_auth_url }}"          # from your vars.yml or env
          region: "{{ os_region_name }}"         # from your vars.yml
          image_uuid: "{{ubuntu_minimal_uuid}}"
          ssh_key_file: "{{local_public_key}}"
        