---
#--------------------------------------------------------------------------------#
# Setup vm nodes with terraform
#--------------------------------------------------------------------------------#
- name: Set up vm nodes with terraform
  hosts: localhost
  vars_files: 
    - ../../../vars.yml    
  tags:
    - bastion-server
  tasks:
    - name: Deploy the bastion
      community.general.terraform:
        project_path: "../../../../terraform/bastion"
        state: present
        force_init: yes
        variables:
          auth_url: "{{ os_auth_url }}"          # from your vars.yml or env
          region: "{{ os_region_name }}"         # from your vars.yml
          image_uuid: "{{ubuntu_minimal_uuid}}"
          ssh_key_file: "{{ local_public_key }}"
          ssh_private_key_file: "{{ local_private_key }}"
          key_pair: "{{ default_key_pair }}"
          cloud_service_vm_IPv4: "{{ cloud_service_vm_IPv4 }}"
          bastion_ipv4: "{{ bastion_insternal_ip }}"
        