os_region_name: RegionOne
os_auth_url: http://mycloud.lan:5000/v3

external_network_name: "public"
local_public_key: "/home/antiamoah890/.ssh/id_ed25519_cluster.pub"
local_private_key: "/home/antiamoah890/.ssh/id_ed25519_cluster"
ubuntu_minimal_uuid: "e46293b4-bdc6-419c-9150-e7d0edb767e5"


#Management vault 
mgmt_vault_ipv4: "10.10.10.100"
mgmt_vault_sg: "mgmt-vault-sg"
mgmt_net: "mgmt_private_net"

# kubernetes
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
cilium_version: "1.15.5"
cilium_lb_ip_range: "172.16.20.200/27"
k3s_master_bind_address: "0.0.0.0"
k3s_mater_01_float_ip: "172.16.20.231"
k3s_mater_01_ipv4: "10.0.0.5"
k3s_worker_01_ipv4: "10.0.0.3"
gpu_worker_01_ipv4: "10.0.0.4"


#Gitlab
gitlab_vm_ipv4: "10.0.0.6" 
swap_size: "8G"